apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: devops-desafio
  newName: mateuslopess/devops-desafio
  newTag: ad16b4945429b3c51cac3807fc6787352295c36d
